# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ "${modulesPath}/installer/scan/not-detected.nix" ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    # USB storage
    "sd_mod"
    "uas"
    "usb_storage"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "boot.shell_on_fail" ];

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enableCryptodisk = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.gfxmodeEfi = "1920x1080";
  boot.loader.grub.theme = pkgs.nixos-grub2-theme;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.extraEntries = ''
    menuentry "Windows" {
      chainloader /efi/Microsoft/Boot/bootmgfw.efi
    }
  '';

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;

  # LUKS
  boot.initrd.luks.devices.crypted.device =
    "/dev/disk/by-uuid/99f098da-1c31-4e83-ae37-f2cde1e7d918";

  fileSystems = {
    "/" = {
      label = "root";
      fsType = "btrfs";
      options = [ "ssd" "space_cache" "subvol=@nixos" ];
    };
    "/nix" = {
      label = "root";
      fsType = "btrfs";
      options = [ "ssd" "space_cache" "compress=zstd" "subvol=@nix" ];
    };
    "/boot" = {
      label = "SYSTEM_DRV";
      fsType = "vfat";
      options = [ "umask=0022" ];
    };
    "/home" = {
      label = "root";
      fsType = "btrfs";
      options = [ "ssd" "space_cache" "compress=zstd" "subvol=@home" ];
    };
    "/ubuntu" = {
      label = "root";
      fsType = "btrfs";
      options = [ "ssd" "space_cache" "compress=zstd" "subvol=@ubuntu" ];
    };
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  services.thermald.enable = true;
}
