# shellcheck shell=bash
# Node and own scripts
export PATH=~/bin/node_modules/.bin:~/bin:$PATH:/usr/local/bin

function _checkSshSock() {
  local s=~/.ssh/socket
  # Make sure we own ~/.ssh before doing anything else
  # Not perfect security but better than nothing
  # Bash should have a "writeable only by me" test
  if [ -w ~/.ssh ] && [ -O ~/.ssh ] && { [ -z "$SSH_AUTH_SOCK" ] || ! timeout 0.5 ssh-add -l >/dev/null 2>&1; }; then
    export SSH_AUTH_SOCK
    for i in "$s"* ~/.ssh/agent/* /tmp/ssh*/*; do
      if [ -S "$i" ] && [ -O "$i" ]; then
        SSH_AUTH_SOCK="$i" timeout 0.5 ssh-add -l >/dev/null 2>&1
        if [ $? -le 1 ]; then
          [ "$i" != $s ] && ln -f -s "$i" $s
          SSH_AUTH_SOCK=$s
          break
        fi
        # Clean up socket?
      fi
    done
    # Only create a new agent if not logging in remotely or sudoing
    if [ -z "$SSH_AUTH_SOCK$SUDO_USER$SSH_CLIENT$SSH2_CLIENT" ]; then
      SSH_AUTH_SOCK=$s
      [ -e "$SSH_AUTH_SOCK" ] && rm "$SSH_AUTH_SOCK"
      eval "$(ssh-agent -a "$SSH_AUTH_SOCK" -s)"
    fi
  fi
}
_checkSshSock

if [ "$XDG_SESSION_TYPE" = wayland ]; then
  export QT_QPA_PLATFORM=wayland
fi

# Not in session vars because they don't get loaded for regular shells
export LC_COLLATE="C"
export LANG="C"
export EDITOR="vi"
export PAGER="less -XF"
export LESS="-j5 -R"
export LESSCHARSET="utf-8"

# entertain me while we load
if type -p fortune >/dev/null; then
  f=$(fortune -c -s computers cookie debian definitions drugs education fortunes goedel humorists law linux literature love magic medicine miscellaneous news off/art off/astrology off/atheism off/black-humor off/cookie off/debian off/definitions off/drugs off/fortunes off/linux off/miscellaneous off/politics off/privates off/racism off/religion off/riddles off/sex off/songs-poems off/vulgarity paradoxum people pets platitudes politics riddles science songs-poems startrek translate-me wisdom work | sed -e 's/(\/nix\/.*\//(/' -e 's/^%//')
  if type -p cowsay >/dev/null; then
    # # original cowsay doesn't have --random
    # function qotd() {
    #   # read -a cows < <(cowsay -l | sed 1d)
    #   local cows=(beavis.zen blowfish bong bud-frogs bunny cower daemon default dragon dragon-and-cow elephant eyes flaming-sheep ghostbusters hellokitty kitty koala llama luke-koala meow milk moofasa moose mutilated ren satanic sheep skeleton small stegosaurus stimpy supermilker surgery three-eyes turkey turtle tux udder vader vader-koala www)
    #   f=$(cowsay -f ${cows[$(($RANDOM*(${#cows[*]})/32768))]} <<<"$f")
    # }
    # qotd
    f=$(cowsay -W 80 --random --aurora <<<"$f")
  fi
  echo "$f"

  unset f
fi

# shortcuts
export SK="stratokit.io" SSK="sync.stratokit.io"

# Automatically run missing commands
export NIX_AUTO_RUN=1

# sudo
# shellcheck source=sudo-wrap.bash
source @sudo-wrap@
alias sudo=sudowrap

# useful functions
function schreen() {
  # we load .bashrc to update ssh agent sock
  ssh "$@" -A -t 'source ~/.bashrc; exec screen -xRR -A -e^Zz -U -O'
}
# shellcheck disable=SC2164
function d() { mkdir -p "$1" && cd "$1"; }
# do not override on macos
if ! type open >&/dev/null; then
  alias open=xdg-open
fi
function duk () { du -k "$@" | sort -n; }
function sduk () { sudo du -k "$@" | sort -n; }
# see the strings of a command
function stmore () { strings -a "$(type -p "$1")" | less; }
# see the source of a command
function whmore () { less "$(type -p "$1")"; }
# set the x window title
function xtitle () { setPS1; echo -e "\033]2;$*\007\c"; }
# Highlight a regexp
function hl () { sed 's/'"$*"'/'"$(tput rev)"'&'"$(tput rmso)"'/g'; }

###-begin-nps.js-completions-###
# from `nps completion` and escape the interpolations and fix the nps path
_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$(nps --get-yargs-completions "${args[@]}")

    mapfile -t COMPREPLY < <(compgen -W "${type_list}" -- "${cur_word}")

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=()
    fi

    return 0
}
complete -o default -F _yargs_completions nps
###-end-nps.js-completions-###

# prompt
if tput setaf 1 &> /dev/null; then
  tput sgr0
  if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
    MAGENTA=$(tput setaf 9)
    ORANGE=$(tput setaf 172)
    # GREEN=$(tput setaf 190)
    PURPLE=$(tput setaf 141)
    WHITE=$(tput setaf 256)
  else
    MAGENTA=$(tput setaf 5)
    ORANGE=$(tput setaf 4)
    # GREEN=$(tput setaf 2)
    PURPLE=$(tput setaf 1)
    WHITE=$(tput setaf 7)
  fi
  # BOLD=$(tput bold)
  RESET=$(tput sgr0)
else
  MAGENTA="\033[1;31m"
  ORANGE="\033[1;33m"
  # GREEN="\033[1;32m"
  PURPLE="\033[1;35m"
  WHITE="\033[1;37m"
  # BOLD=""
  RESET="\033[m"
fi

# Fastest possible way to check if repo is dirty. a savior for the WebKit repo.
function parse_git_dirty() {
  git diff --quiet --ignore-submodules HEAD 2>/dev/null || echo '*'
}

function parse_git_branch() {
  local e=$?
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/" -e 's/^/ on /'
  return $e
}

# setPS1 [xtitle]
function _err() {
  local e=$?
  if [ $e -ne 0 ]; then
    echo "😢  ERR $e "
  fi
  return $e
}
function setPS1 () {
  local extra x
  if [ "$USER" != @user@ ]; then
    extra="\[$PURPLE\]$USER@\[$WHITE\]"
    if [ "$USER" = root ]; then
      export TMOUT=180
    fi
  fi
  if [ "$HOSTNAME" != @mainHost@ ]; then
    extra="$extra\[$ORANGE\]$HOSTNAME\[$WHITE\] "
  fi
  case "$TERM" in
    vt320|xterm*)
      if [ "$HOSTNAME" != @mainHost@ ]; then
        x='\[\e]0;\h:\w\a\]'
      else
        x='\[\e]0;\w\a\]'
      fi
      ;;
    screen)
      x='\[\ek\h\e\\\]'
      ;;
  esac
  PS1="$x"'🍀 🐚 \[$WHITE\] \d \t \[$MAGENTA\]$(_err)\[$WHITE\]'"$extra"'\[$ORANGE\]\w\[$PURPLE\]$(parse_git_branch)\[$WHITE\]\n\! \$ \[$RESET\]'
  #export PS1="$x$BOLD=== \d \t\$(_err) \w\n=== \! $extra\h\['`tput sgr0`'\] \W'$git' \$ "
}

setPS1
